name=input("What is your name? ")
#colour=input("What is your favorite colour? ")
by=input("What is your birth year? ")
age = 2021 - int(by)
#print(name+" likes "+colour)
print(name+" age is "+str(age))
print("HAPPY BIRTHDAY   ^")
print("HAPPY BIRTHDAY  ()")
print("                ||")
print("            -----------")
print("             |       |")
print("             |       |")
print("            ----------")

